server:
  port: 8089

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://prod-db:5432/zenwk
      username: prod_user
      password: prod_pass
logging:
  level:
    root: ERROR

security:
  jwt:
    secret: ${JWT_SECRET:U3VwM1I1Y1IzdFA0czVXMHJEIFwU3VwM1I1Y1IzdFA0czVXMHJEIFw=}