server:
  port: 8089

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://test-db:5432/zenwk_test
      username: test_user
      password: test_pass
security:
  test-config:
    config.enabled: true
  jwt:
    secret: ${JWT_SECRET:U3VwM1I1Y1IzdFA0czVXMHJEIFwU3VwM1I1Y1IzdFA0czVXMHJEIFw=}