server:
  port: 8089 
  ssl:
    enabled: true
    key-store: classpath:myserver.keystore
    key-store-password: 123456  # Contraseña del keystore
    key-password: 123456       # Contraseña de la clave privada
    key-alias: myserver

app:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://postgres:5432/zenwk
      username: calegria
      password: calegria
logging:
  level:
    root: INFO

security:
  jwt:
    secret: ${JWT_SECRET:U3VwM1I1Y1IzdFA0czVXMHJEIFwU3VwM1I1Y1IzdFA0czVXMHJEIFw=}
    